const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  patients: {
    getAll: () => ipcRenderer.invoke('patients:getAll'),
    get: (id) => ipcRenderer.invoke('patients:get', id),
    search: (q) => ipcRenderer.invoke('patients:search', q),
    create: (p) => ipcRenderer.invoke('patients:create', p),
    update: (p) => ipcRenderer.invoke('patients:update', p),
    delete: (id) => ipcRenderer.invoke('patients:delete', id),
    getByProvider: (name) => ipcRenderer.invoke('patients:getByProvider', name),
    transfer: (obj) => ipcRenderer.invoke('patients:transfer', obj),
    undoTransfer: (id) => ipcRenderer.invoke('patients:undoTransfer', id),
  },
  operatories: {
    getAll: () => ipcRenderer.invoke('operatories:getAll'),
    create: (o) => ipcRenderer.invoke('operatories:create', o),
    update: (o) => ipcRenderer.invoke('operatories:update', o),
    delete: (id) => ipcRenderer.invoke('operatories:delete', id),
  },
  appointments: {
    getAll: () => ipcRenderer.invoke('appointments:getAll'),
    getByDate: (date) => ipcRenderer.invoke('appointments:getByDate', date),
    getByPatient: (pid) => ipcRenderer.invoke('appointments:getByPatient', pid),
    getByProvider: (obj) => ipcRenderer.invoke('appointments:getByProvider', obj),
    getWaitingRoom: () => ipcRenderer.invoke('appointments:getWaitingRoom'),
    seatPatient: (obj) => ipcRenderer.invoke('appointments:seatPatient', obj),
    dismissPatient: (id) => ipcRenderer.invoke('appointments:dismissPatient', id),
    removeArrival: (id) => ipcRenderer.invoke('appointments:removeArrival', id),
    getUnscheduled: () => ipcRenderer.invoke('appointments:getUnscheduled'),
    getASAP: () => ipcRenderer.invoke('appointments:getASAP'),
    getPinboard: () => ipcRenderer.invoke('appointments:getPinboard'),
    getRecallDue: () => ipcRenderer.invoke('appointments:getRecallDue'),
    create: (a) => ipcRenderer.invoke('appointments:create', a),
    update: (a) => ipcRenderer.invoke('appointments:update', a),
    delete: (id) => ipcRenderer.invoke('appointments:delete', id),
    sendToPinboard: (id) => ipcRenderer.invoke('appointments:sendToPinboard', id),
    sendToUnscheduled: (id) => ipcRenderer.invoke('appointments:sendToUnscheduled', id),
    scheduleFromPinboard: (o) => ipcRenderer.invoke('appointments:scheduleFromPinboard', o),
    markASAP: (id) => ipcRenderer.invoke('appointments:markASAP', id),
    updateStatus: (o) => ipcRenderer.invoke('appointments:updateStatus', o),
    updateConfirmed: (o) => ipcRenderer.invoke('appointments:updateConfirmed', o),
    updateArrival: (o) => ipcRenderer.invoke('appointments:updateArrival', o),
  },
  blockouts: {
    getByDate: (date) => ipcRenderer.invoke('blockouts:getByDate', date),
    create: (b) => ipcRenderer.invoke('blockouts:create', b),
    delete: (id) => ipcRenderer.invoke('blockouts:delete', id),
  },
  treatments: {
    getByPatient: (pid) => ipcRenderer.invoke('treatments:getByPatient', pid),
    create: (t) => ipcRenderer.invoke('treatments:create', t),
    update: (t) => ipcRenderer.invoke('treatments:update', t),
    delete: (id) => ipcRenderer.invoke('treatments:delete', id),
  },
  billing: {
    getAll: () => ipcRenderer.invoke('billing:getAll'),
    getByPatient: (pid) => ipcRenderer.invoke('billing:getByPatient', pid),
    getByProvider: (name) => ipcRenderer.invoke('billing:getByProvider', name),
    create: (b) => ipcRenderer.invoke('billing:create', b),
    update: (b) => ipcRenderer.invoke('billing:update', b),
    delete: (id) => ipcRenderer.invoke('billing:delete', id),
  },
  providers: {
    getAll: () => ipcRenderer.invoke('providers:getAll'),
    getUserForProvider: (name) => ipcRenderer.invoke('providers:getUserForProvider', name),
    get: (id) => ipcRenderer.invoke('providers:get', id),
    create: (p) => ipcRenderer.invoke('providers:create', p),
    update: (p) => ipcRenderer.invoke('providers:update', p),
    delete: (id) => ipcRenderer.invoke('providers:delete', id),
    getAvailability: () => ipcRenderer.invoke('providers:getAvailability'),
    getAppointments: (name, date) => ipcRenderer.invoke('providers:getAppointments', { name, date }),
  },
  stats: {
    dashboard: (providerName) => ipcRenderer.invoke('stats:dashboard', providerName),
  },
  users: {
    login: (creds) => ipcRenderer.invoke('users:login', creds),
    getAll: () => ipcRenderer.invoke('users:getAll'),
    getByProvider: (name) => ipcRenderer.invoke('users:getByProvider', name),
    create: (u) => ipcRenderer.invoke('users:create', u),
    update: (u) => ipcRenderer.invoke('users:update', u),
    delete: (id) => ipcRenderer.invoke('users:delete', id),
    grantFullAccess: (id) => ipcRenderer.invoke('users:grantFullAccess', id),
    revokeFullAccess: (id) => ipcRenderer.invoke('users:revokeFullAccess', id),
    changePassword: (obj) => ipcRenderer.invoke('users:changePassword', obj),
  },
});